# Generated by Django 3.2.13 on 2022-10-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('acc_num', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.state')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ward')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
